routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() {
    return redirect(route('login'));
});
Auth::routes();
// Route::get('/numberRandom', 'UserController@numberRandom')->name('users.numberRandom');
Route::group(['middleware' => 'auth'], function() {

    Route::group(['middleware' => ['role:admin']], function () {
        Route::resource('/role', 'RoleController')->except([
            'create', 'show', 'edit', 'update'
        ]);

        Route::resource('/users', 'UserController')->except([
            'show'
        ]);
        Route::get('/users/roles/{id}', 'UserController@roles')->name('users.roles');
        Route::put('/users/roles/{id}', 'UserController@setRole')->name('users.set_role');
        Route::post('/users/permission', 'UserController@addPermission')->name('users.add_permission');
        Route::get('/users/role-permission', 'UserController@rolePermission')->name('users.roles_permission');
        Route::put('/users/permission/{role}', 'UserController@setRolePermission')->name('users.setRolePermission');
        Route::post('/wpJson/fetch', 'UserController@fetch')->name('wpJson.fetch');
        //Route::get('/transaksi', 'TransaksiController@index')->name('transaksi.index');

    });

    Route::group(['middleware' => ['role:admin|wajib_pajak']], function () {
        Route::get('/transaksi', 'TransaksiController@index')->name('transaksi.index');
        Route::get('/transaksi/rekapbulanan', 'TransaksiController@rekapbulanan')->name('transaksi.rekapbulanan');
        Route::get('/transaksi/transaksiwp', 'TransaksiController@transaksiwp')->name('transaksi.transaksiwp');
        Route::get('/transaksi/wptidaktermonitor', 'TransaksiController@wptidaktermonitor')->name('transaksi.wptidaktermonitor');

    });

    // Route::group(['middleware' => ['role:admin,Wajib Pajak']], function() {
    //     Route::get('/transaksi', 'TransaksiController@index')->name('transaksi.index');
    // });

    // Route::group(['middleware' => ['permission:show products|create products|delete products']], function() {
    //     Route::resource('/kategori', 'CategoryController')->except([
    //         'create', 'show'
    //     ]);
    //     Route::resource('/produk', 'ProductController');
    // });

    // Route::group(['middleware' => ['role:kasir']], function() {
    //     Route::get('/transaksi', 'OrderController@addOrder')->name('order.transaksi');
    //     Route::get('/checkout', 'OrderController@checkout')->name('order.checkout');
    //     Route::post('/checkout', 'OrderController@storeOrder')->name('order.storeOrder');
    // });

    // Route::group(['middleware' => ['role:admin,kasir']], function() {
    //     Route::get('/order', 'OrderController@index')->name('order.index');
    //     Route::get('/order/pdf/{invoice}', 'OrderController@invoicePdf')->name('order.pdf');
    //     Route::get('/order/excel/{invoice}', 'OrderController@invoiceExcel')->name('order.excel');
    // });

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    public function index()
    {
        $role = Role::orderBy('created_at', 'DESC')->paginate(10);
        return view('role.index', compact('role'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50'
        ]);

        $role = Role::firstOrCreate(['name' => $request->name]);
        return redirect()->back()->with(['success' => 'Role: <strong>' . $role->name . '</strong> Ditambahkan']);
    }

    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();
        return redirect()->back()->with(['success' => 'Role: <strong>' . $role->name . '</strong> Dihapus']);
    }
}

resources/views/role/index.blade.php
@extends('layouts.master')

@section('title')
    <title>Manajemen Role</title>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Manajemen Role</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-item active">Role</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4">
                        @card
                            @slot('title')
                            Tambah
                            @endslot

                            @if (session('error'))
                                @alert(['type' => 'danger'])
                                    {!! session('error') !!}
                                @endalert
                            @endif

                            <form role="form" action="{{ route('role.store') }}" method="POST">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Role</label>
                                    <input type="text"
                                    name="name"
                                    class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" id="name" required>
                                </div>
                            @slot('footer')
                                <div class="card-footer">
                                    <button class="btn btn-primary">Simpan</button>
                                </div>
                            </form>
                            @endslot
                        @endcard
                    </div>
                    <div class="col-md-8">
                        @card
                            @slot('title')
                            List Role
                            @endslot

                            @if (session('success'))
                                @alert(['type' => 'success'])
                                    {!! session('success') !!}
                                @endalert
                            @endif

                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <td>#</td>
                                            <td>Role</td>
                                            <td>Guard</td>
                                            <td>Created At</td>
                                            <td>Aksi</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $no = 1; @endphp
                                        @forelse ($role as $row)
                                        <tr>
                                            <td>{{ $no++ }}</td>
                                            <td>{{ $row->name }}</td>
                                            <td>{{ $row->guard_name }}</td>
                                            <td>{{ $row->created_at }}</td>
                                            <td>
                                                <form action="{{ route('role.destroy', $row->id) }}" method="POST">
                                                    @csrf
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="5" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>

                            <div class="float-right">
                                {!! $role->links() !!}
                            </div>
                            @slot('footer')

                            @endslot
                        @endcard
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection